<?php
//Die if accessed directly
defined('ABSPATH') || die('Shame on you');

if (function_exists('acf_add_local_field_group')) :

  acf_add_local_field_group(array(
    'key' => 'group_55397e6312ba1',
    'title' => 'Baner',
    'fields' => array(
      array(
        'key' => 'field_55397e6f3a67d',
        'label' => 'Bilde',
        'name' => 'image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'url',
        'preview_size' => 'full',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => 'jpg, jpeg, webp',
      ),
      array(
        'key' => 'field_55397ea53a67e',
        'label' => 'Underlag',
        'name' => 'surface',
        'type' => 'select',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'astroturf' => 'Kunstgress',
          'gravel_pitch' => 'Grus',
          'parquet' => 'Parkett',
          'concrete' => 'Betong',
        ),
        'default_value' => array(
          'astroturf' => 'Kunstgress',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 1,
        'ajax' => 0,
        'placeholder' => '',
        'disabled' => 0,
        'readonly' => 0,
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_55397eee3a67f',
        'label' => 'Adresse',
        'name' => 'address',
        'type' => 'google_map',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'center_lat' => '',
        'center_lng' => '',
        'zoom' => '',
        'height' => '',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'pitch',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => array(
      0 => 'permalink',
      1 => 'the_content',
      2 => 'excerpt',
      3 => 'custom_fields',
      4 => 'discussion',
      5 => 'comments',
      6 => 'revisions',
      7 => 'slug',
      8 => 'author',
      9 => 'format',
      10 => 'page_attributes',
      11 => 'featured_image',
      12 => 'categories',
      13 => 'tags',
      14 => 'send-trackbacks',
    ),
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5539864c3a238',
    'title' => 'Kamper',
    'fields' => array(
      array(
        'key' => 'field_553996e401243',
        'label' => 'Kampinfo',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5539868a27be4',
        'label' => 'Hjemmelag',
        'name' => 'home_team',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'club',
        ),
        'taxonomy' => array(),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => 1,
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_553986be27be5',
        'label' => 'Bortelag',
        'name' => 'away_team',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'club',
        ),
        'taxonomy' => array(),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => 1,
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_55398c3d2ab0b',
        'label' => 'Tidspunkt',
        'name' => 'date_time',
        'type' => 'date_time_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'display_format' => 'd.m.Y H.i',
        'return_format' => 'Y-m-d H:i:s',
        'first_day' => 1,
      ),
      array(
        'key' => 'field_55398a8fbcc47',
        'label' => 'Bane',
        'name' => 'pitch',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => 50,
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'pitch',
        ),
        'taxonomy' => array(),
        'filters' => '',
        'elements' => '',
        'min' => 0,
        'max' => 1,
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_553999e095c5d',
        'label' => 'Tilskuere',
        'name' => 'attendance',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_56649d02b485f',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 2,
        'new_lines' => 'br',
      ),
      array(
        'key' => 'field_553999f495c5e',
        'label' => 'Forhold',
        'name' => 'weather',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_56649d02b485f',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => 2,
        'new_lines' => 'br',
      ),
      array(
        'key' => 'field_5611b94e32f1c',
        'label' => 'Tilstede',
        'name' => 'present',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_56649d02b485f',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'player',
        ),
        'taxonomy' => array(),
        'filters' => array(
          0 => 'search',
          1 => 'post_type',
          2 => 'taxonomy',
        ),
        'elements' => '',
        'min' => '',
        'max' => '',
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_55399374c7c6e',
        'label' => '1. omgang',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_56649d02b485f',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
          array(
            array(
              'field' => 'field_5b5701e99d9dd',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_55399264f729d',
        'label' => 'Mål og assist',
        'name' => 'goals_assists_first_half',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'block',
        'button_label' => 'Legg til mål',
        'sub_fields' => array(
          array(
            'key' => 'field_55399d91caaa9',
            'label' => 'Mål til',
            'name' => 'goal_for',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'kampbart' => 'Kampbart',
              'opponent' => 'Motstander',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
          ),
          array(
            'key' => 'field_5539927df729e',
            'label' => 'Målscorer',
            'name' => 'goal_scorer_first_half',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399d91caaa9',
                  'operator' => '==',
                  'value' => 'kampbart',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'player',
            ),
            'taxonomy' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
          array(
            'key' => 'field_56649128aa9ad',
            'label' => 'Assist',
            'name' => 'assist',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399d91caaa9',
                  'operator' => '==',
                  'value' => 'kampbart',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'player_assist' => 'Spillerassist',
              'free_text_assist' => 'Fritekst',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
          ),
          array(
            'key' => 'field_553993d4c7c6f',
            'label' => 'Spillerassist',
            'name' => 'assist_first_half',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399d91caaa9',
                  'operator' => '==',
                  'value' => 'kampbart',
                ),
                array(
                  'field' => 'field_56649128aa9ad',
                  'operator' => '==',
                  'value' => 'player_assist',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'player',
            ),
            'taxonomy' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
          array(
            'key' => 'field_56649111aa9ac',
            'label' => 'Fritekst',
            'name' => 'assist_first_half_text',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399d91caaa9',
                  'operator' => '==',
                  'value' => 'kampbart',
                ),
                array(
                  'field' => 'field_56649128aa9ad',
                  'operator' => '==',
                  'value' => 'free_text_assist',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => 50,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array(
            'key' => 'field_55399defcaaaa',
            'label' => 'Mål til motstander',
            'name' => 'opponent_goal',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399d91caaa9',
                  'operator' => '==',
                  'value' => 'opponent',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'club',
            ),
            'taxonomy' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
        ),
      ),
      array(
        'key' => 'field_566c9d6565f1f',
        'label' => 'Kort',
        'name' => 'cards_first_half',
        'type' => 'radio',
        'instructions' => 'Ble det noen kort i denne omgangen?',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'no' => 'Nei',
          'yes' => 'Ja',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'no',
        'layout' => 'horizontal',
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_5b570281d02fb',
        'label' => 'Kort (ny)',
        'name' => 'cards_first_half',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_566c9d6565f1f',
              'operator' => '==',
              'value' => 'yes',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Legg til kort',
        'sub_fields' => array(
          array(
            'key' => 'field_5b5702f9d0302',
            'label' => 'card_first_half',
            'name' => 'card_first_half',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'player',
            ),
            'taxonomy' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
          array(
            'key' => 'field_5b57035dd0303',
            'label' => 'card_colour_first_half',
            'name' => 'card_colour_first_half',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'yellow' => 'Gult',
              'red' => 'Rødt',
            ),
            'default_value' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 1,
            'return_format' => 'value',
            'placeholder' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_55399891cd081',
        'label' => 'Gult kort',
        'name' => 'yellow_card_first_half',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_566c9d6565f1f',
              'operator' => '==',
              'value' => 'yes',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'player',
        ),
        'taxonomy' => array(
          0 => 'status:aktiv',
        ),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => '',
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_5539988bcd080',
        'label' => 'Rødt kort',
        'name' => 'red_card_first_half',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_566c9d6565f1f',
              'operator' => '==',
              'value' => 'yes',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'player',
        ),
        'taxonomy' => array(
          0 => 'status:aktiv',
        ),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => '',
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_5539952410f93',
        'label' => '2. omgang',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_56649d02b485f',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
          array(
            array(
              'field' => 'field_5b5701e99d9dd',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5539952d10f94',
        'label' => 'Mål og assist',
        'name' => 'goals_assists_second_half',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'block',
        'button_label' => 'Legg til mål',
        'sub_fields' => array(
          array(
            'key' => 'field_55399b52a9a63',
            'label' => 'Mål til',
            'name' => 'goal_for',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'kampbart' => 'Kampbart',
              'opponent' => 'Motstander',
            ),
            'allow_null' => 0,
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'return_format' => 'value',
          ),
          array(
            'key' => 'field_5539952d10f95',
            'label' => 'Målscorer',
            'name' => 'goal_scorer_second_half',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399b52a9a63',
                  'operator' => '==',
                  'value' => 'kampbart',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'player',
            ),
            'taxonomy' => array(
              // 0 => 'status:aktiv',
            ),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
          array(
            'key' => 'field_566494b79d673',
            'label' => 'Assist',
            'name' => 'assist_second_half_text',
            'type' => 'radio',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399b52a9a63',
                  'operator' => '==',
                  'value' => 'kampbart',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => 50,
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'player_assist' => 'Spillerassist',
              'free_text_assist' => 'Fritekst',
            ),
            'other_choice' => 0,
            'save_other_choice' => 0,
            'default_value' => '',
            'layout' => 'horizontal',
            'allow_null' => 0,
            'return_format' => 'value',
          ),
          array(
            'key' => 'field_5539952d10f96',
            'label' => 'Spillerassist',
            'name' => 'assist_second_half',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399b52a9a63',
                  'operator' => '==',
                  'value' => 'kampbart',
                ),
                array(
                  'field' => 'field_566494b79d673',
                  'operator' => '==',
                  'value' => 'player_assist',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'player',
            ),
            'taxonomy' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
          array(
            'key' => 'field_5664953f9d675',
            'label' => 'Fritekst',
            'name' => 'assist_second_half_text',
            'type' => 'textarea',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399b52a9a63',
                  'operator' => '==',
                  'value' => 'kampbart',
                ),
                array(
                  'field' => 'field_566494b79d673',
                  'operator' => '==',
                  'value' => 'free_text_assist',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => 50,
              'class' => '',
              'id' => '',
            ),
            'default_value' => '',
            'placeholder' => '',
            'maxlength' => '',
            'rows' => 2,
            'new_lines' => '',
            'readonly' => 0,
            'disabled' => 0,
          ),
          array(
            'key' => 'field_55399c3feacc7',
            'label' => 'Mål til motstander',
            'name' => 'opponent_goal',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => array(
              array(
                array(
                  'field' => 'field_55399b52a9a63',
                  'operator' => '==',
                  'value' => 'opponent',
                ),
              ),
            ),
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'club',
            ),
            'taxonomy' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
        ),
      ),
      array(
        'key' => 'field_566c9e9a98df1',
        'label' => 'Kort',
        'name' => 'cards_second_half',
        'type' => 'radio',
        'instructions' => 'Ble det noen kort i denne omgangen?',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'no' => 'Nei',
          'yes' => 'Ja',
        ),
        'allow_null' => 0,
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => 'no',
        'layout' => 'horizontal',
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_5b47370f205cd',
        'label' => 'Kort (ny)',
        'name' => 'cards_second_half',
        'type' => 'repeater',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_566c9e9a98df1',
              'operator' => '==',
              'value' => 'yes',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => '',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Legg til kort',
        'sub_fields' => array(
          array(
            'key' => 'field_5b47376d205ce',
            'label' => 'card_second_half',
            'name' => 'card_second_half',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'player',
            ),
            'taxonomy' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
          array(
            'key' => 'field_5b47382f205cf',
            'label' => 'farge',
            'name' => 'card_colour_second_half',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'yellow' => 'Gult',
              'red' => 'Rødt',
            ),
            'default_value' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 1,
            'return_format' => 'value',
            'placeholder' => '',
          ),
        ),
      ),
      array(
        'key' => 'field_553997ebb763f',
        'label' => 'Gult kort',
        'name' => 'yellow_card_second_half',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_566c9e9a98df1',
              'operator' => '==',
              'value' => 'yes',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'player',
        ),
        'taxonomy' => array(),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => '',
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_5539987bcd07e',
        'label' => 'Rødt kort',
        'name' => 'red_card_second_half',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_566c9e9a98df1',
              'operator' => '==',
              'value' => 'yes',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'player',
        ),
        'taxonomy' => array(
          0 => 'status:aktiv',
        ),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => '',
        'return_format' => 'object',
      ),
      array(
        'key' => 'field_5b562f29b0299',
        'label' => 'Mangefull rapport',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'top',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5b572345c5832',
        'label' => 'Bestem resultat',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_5b5701e99d9dd',
        'label' => 'Kun resultat',
        'name' => 'result_only',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '25',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5b5701e00d9dd',
        'label' => 'Kun fulltidsresultat',
        'name' => 'result_only_fulltime',
        'type' => 'true_false',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '25',
          'class' => '',
          'id' => '',
        ),
        'message' => '',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5664aa008435c',
        'label' => 'Fulltid',
        'name' => 'result_fulltime',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '25',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '0–0',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b562f79b029b',
        'label' => 'Pause',
        'name' => 'result_pause',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_5b5701e00d9dd',
              'operator' => '!=',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '20',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '0–0',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b572345c4592',
        'label' => 'Walkover',
        'name' => '',
        'type' => 'accordion',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'open' => 0,
        'multi_expand' => 0,
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_56649d02b485f',
        'label' => 'Walkover',
        'name' => 'walkover',
        'type' => 'true_false',
        'instructions' => 'Hvis ett av lagene ikke møtte opp til kamp så er dette riktig valg. Det er mulig å sette resultat på kampen. Hvis ikke vil resultatet automatisk bli satt til 0–0.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '50',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Kryss av hvis kampen har endt i walkover.',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5b56fe5dc8adf',
        'label' => 'Resultat',
        'name' => 'walkover_result',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_56649d02b485f',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '25',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '0–0',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
      ),
      array(
        'key' => 'field_5b56fe5dc8ceb',
        'label' => 'Vinner på walkover',
        'name' => 'walkover_winner',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_56649d02b485f',
              'operator' => '==',
              'value' => '1',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '25',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'kampbart' => 'Kampbart',
          'opponent' => 'Motstander',
        ),
        'default_value' => array(),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 1,
        'ajax' => 1,
        'return_format' => 'value',
        'placeholder' => '',
      ),
      array(
        'key' => 'field_5b56f91f7d105',
        'label' => 'Lag trukket',
        'name' => 'team_whitdrawed',
        'type' => 'true_false',
        'instructions' => 'Uavhengig av om kampen har blitt spilt så kryss ut dette valget om laget har blitt trukket fra serien.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'message' => 'Laget er trukket fra serien',
        'default_value' => 0,
        'ui' => 1,
        'ui_on_text' => '',
        'ui_off_text' => '',
      ),
      array(
        'key' => 'field_5b570653cb32e',
        'label' => 'Kort',
        'name' => 'cards',
        'type' => 'repeater',
        'instructions' => 'Det ble gitt kort i kampen, men vi vet ikke i hvilken omgang.',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'collapsed' => 'field_5b57069dcb32f',
        'min' => 0,
        'max' => 0,
        'layout' => 'table',
        'button_label' => 'Legg til kort',
        'sub_fields' => array(
          array(
            'key' => 'field_5b57069dcb32f',
            'label' => 'Spiller',
            'name' => 'card_player',
            'type' => 'post_object',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'post_type' => array(
              0 => 'player',
            ),
            'taxonomy' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'return_format' => 'object',
            'ui' => 1,
          ),
          array(
            'key' => 'field_5b5706becb330',
            'label' => 'Farge',
            'name' => 'card_colour',
            'type' => 'select',
            'instructions' => '',
            'required' => 0,
            'conditional_logic' => 0,
            'wrapper' => array(
              'width' => '50',
              'class' => '',
              'id' => '',
            ),
            'choices' => array(
              'yellow' => 'Gult',
              'red' => 'Rødt',
            ),
            'default_value' => array(),
            'allow_null' => 0,
            'multiple' => 0,
            'ui' => 1,
            'ajax' => 1,
            'return_format' => 'value',
            'placeholder' => '',
          ),
        ),
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'fixture',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5611b70e91d20',
    'title' => 'Kamprapport',
    'fields' => array(
      array(
        'key' => 'field_5611b722ce0d9',
        'label' => 'Rapport',
        'name' => 'match_report',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'fixture',
        ),
        'taxonomy' => array(),
        'filters' => array(
          0 => 'search',
          1 => 'taxonomy',
        ),
        'elements' => '',
        'min' => '',
        'max' => 1,
        'return_format' => 'object',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_category',
          'operator' => '==',
          'value' => 'category:kamprapporter',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'acf_after_title',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_55787008a2b5b',
    'title' => 'Ligaer',
    'fields' => array(
      array(
        'key' => 'field_5578701b8af93',
        'label' => 'Motstandere',
        'name' => 'opponents',
        'type' => 'relationship',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'post_type' => array(
          0 => 'club',
        ),
        'taxonomy' => array(),
        'filters' => array(
          0 => 'search',
        ),
        'elements' => '',
        'min' => '',
        'max' => '',
        'return_format' => 'object',
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'league',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_55397fa60a5b0',
    'title' => 'Sideinnstillinger',
    'fields' => array(
      array(
        'key' => 'field_55397fc483cbc',
        'label' => '404',
        'name' => '',
        'type' => 'tab',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'placement' => 'left',
        'endpoint' => 0,
      ),
      array(
        'key' => 'field_55397fd883cbd',
        'label' => '404',
        'name' => '404',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'full',
        'media_upload' => 1,
        'delay' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'options_page',
          'operator' => '==',
          'value' => 'kampbart_acf_general',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_55399f019a0df',
    'title' => 'Spillere',
    'fields' => array(
      array(
        'key' => 'field_553be12657bcb',
        'label' => 'Status',
        'name' => 'status',
        'type' => 'select',
        'instructions' => '',
        'required' => 1,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'active' => 'Aktiv',
          'retired' => 'Barten på hylla',
        ),
        'default_value' => array(
          '' => '',
        ),
        'allow_null' => 0,
        'multiple' => 0,
        'ui' => 0,
        'ajax' => 0,
        'placeholder' => '',
        'disabled' => 0,
        'readonly' => 0,
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_553be16a57bcc',
        'label' => 'Medlemskap',
        'name' => 'active_member',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_553be12657bcb',
              'operator' => '==',
              'value' => 'active',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'full_member' => 'Fullbart',
          'new_signing' => 'Dunbart',
          'part_time_member' => 'Løsbart',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
        'allow_null' => 0,
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_553be20057bcd',
        'label' => 'Medlemskap',
        'name' => 'retired_member',
        'type' => 'radio',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => array(
          array(
            array(
              'field' => 'field_553be12657bcb',
              'operator' => '==',
              'value' => 'retired',
            ),
          ),
        ),
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'full_member' => 'Fullbart',
          'part_time_member' => 'Løsbart',
        ),
        'other_choice' => 0,
        'save_other_choice' => 0,
        'default_value' => '',
        'layout' => 'horizontal',
        'allow_null' => 0,
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_55399f23638d3',
        'label' => 'Portrettfoto',
        'name' => 'image',
        'type' => 'image',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'return_format' => 'array',
        'preview_size' => 'thumbnail',
        'library' => 'all',
        'min_width' => '',
        'min_height' => '',
        'min_size' => '',
        'max_width' => '',
        'max_height' => '',
        'max_size' => '',
        'mime_types' => '',
      ),
      array(
        'key' => 'field_55399f44638d4',
        'label' => 'Draktnummer',
        'name' => 'shirt_number',
        'type' => 'number',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'min' => '',
        'max' => '',
        'step' => 1,
        'readonly' => 0,
        'disabled' => 0,
      ),
      array(
        'key' => 'field_55399f65638d5',
        'label' => 'Draktnavn',
        'name' => 'shirt_name',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array(
        'key' => 'field_55399f7f638d6',
        'label' => 'Født',
        'name' => 'dob',
        'type' => 'date_picker',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'display_format' => 'd/m/Y',
        'return_format' => 'd.m.Y',
        'first_day' => 1,
      ),
      array(
        'key' => 'field_55399fa3638d7',
        'label' => 'Posisjon',
        'name' => 'position',
        'type' => 'checkbox',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'choices' => array(
          'keeper' => 'Målvakt',
          'defense' => 'Forsvar',
          'back' => 'Back',
          'midfield' => 'Midtbane',
          'attacker' => 'Spiss',
        ),
        'default_value' => array(
          '' => '',
        ),
        'layout' => 'horizontal',
        'toggle' => 0,
        'allow_custom' => 0,
        'save_custom' => 0,
        'return_format' => 'value',
      ),
      array(
        'key' => 'field_55399ffe638d8',
        'label' => 'Tidligere klubber',
        'name' => 'former_clubs',
        'type' => 'text',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'prepend' => '',
        'append' => '',
        'maxlength' => '',
        'readonly' => 0,
        'disabled' => 0,
      ),
      array(
        'key' => 'field_5539a018638d9',
        'label' => 'Beste Kampbartminne',
        'name' => 'best_memory',
        'type' => 'textarea',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'placeholder' => '',
        'maxlength' => '',
        'rows' => '',
        'new_lines' => 'wpautop',
        'readonly' => 0,
        'disabled' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'post_type',
          'operator' => '==',
          'value' => 'player',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

  acf_add_local_field_group(array(
    'key' => 'group_5b571748f2e28',
    'title' => 'Turneringer',
    'fields' => array(
      array(
        'key' => 'field_5b571765f75b2',
        'label' => 'Ekstra innhold',
        'name' => 'tournament_content',
        'type' => 'wysiwyg',
        'instructions' => '',
        'required' => 0,
        'conditional_logic' => 0,
        'wrapper' => array(
          'width' => '',
          'class' => '',
          'id' => '',
        ),
        'default_value' => '',
        'tabs' => 'all',
        'toolbar' => 'basic',
        'media_upload' => 0,
        'delay' => 0,
      ),
    ),
    'location' => array(
      array(
        array(
          'param' => 'taxonomy',
          'operator' => '==',
          'value' => 'tournament',
        ),
      ),
    ),
    'menu_order' => 0,
    'position' => 'normal',
    'style' => 'default',
    'label_placement' => 'top',
    'instruction_placement' => 'label',
    'hide_on_screen' => '',
    'active' => 1,
    'description' => '',
  ));

endif;

/** ACF init */
// function acf_options_page () {

// 	if ( ! function_exists( 'acf_options_page' ) ) {
// 		return;
// 	}

// 	acf_add_options_page( array(
// 		'page_title'  => __('Site settings', 'moustache'),
// 		'menu_title' => __('Site settings', 'moustache'),
// 		'capability' => 'edit_posts',
// 		'menu_slug' => 'dekode_acf_settings',
// 		'position' => false,
// 		'icon_url' => 'dashicons-admin-settings'
// 	) );

// 	acf_add_options_page( array(
// 		'page_title'  => __('General settings', 'moustache'),
// 		'menu_title' => __('General settings', 'moustache'),
// 		'capability' => 'edit_posts',
// 		'menu_slug' => 'dekode_acf_general',
// 		'parent' => 'dekode_acf_settings',
// 		'position' => false,
// 		'icon_url' => 'dashicons-admin-settings',
// 		'redirect' => false
// 	) );

// }
// add_action( 'init', 'acf_options_page' );
